services:
  - type: web
    name: clip-comparador
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_simple.py
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        generateValue: true